### ISSUE TITLE
Walls around edges

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#10]
Suggestion - add walls around the edges of the level. Now it's not that obvious where the level end.

**Comment by anaseto** [comment]
Oh, I thought the lines with box characters ` ─` and `│` at the bottom and right were enough. Otherwise I would have to make the algorithms generate only walls on the edges, and we'lle lose a couple of lines and columns (with a little screen and a large font there's not much space left). Or maybe I'm missing something?

**Comment by erf** [comment]
For me it's like the box characters encloses the level map, but they are not the same as the walls. It's almost like i'm expecting it to be possible to move further down the map - levels larger than the bounding box would actually be pretty cool, but then it would probably make more sense to have the camera center around the player as he moves around. Hmm. Sorry if i'm of topic now 😄

**Comment by anaseto** [comment]
Oh, I see. Yeah, in games with a semi-scrolling camera this would be rather unintuitive :) 
That said, in Boohu, as the map is always static and stairs are the only way down, this can only be really surprising first time ;)

And yes, I could have used a centered camera too like in DCSS, I actually thought a little about it, and I chose to go with the classic nethack-like or brogue-like little static map, because at the time it seemed to me it was a good fit for a little coffee-break roguelike, but the centered camera might have been more sensible, dunno. There's at least one positive side effect with the current approach: we don't need a minimap :)

**Comment by erf** [comment]
I guess my bad memory plays tricks on me :P 

A centered camera map would might be better for smaller screens, as you would not need to show the whole map all the time. Screw minimap, keep it hardcore ;)

**Comment by anaseto** [comment]
I will actually keep this in mind, because it could be indeed interesting to have perhaps an option to turn a centered camera mode on, though this might require quite a few UI code refactorings, probably.

> Screw minimap, keep it hardcore ;)

Haha, this would give a labyrinth feeling :)

**Comment by erf** [comment]
> I will actually keep this in mind

Sounds like a cool idea!

> Haha, this would give a labyrinth feeling :)

Yeah, but depends on the level size :)

**Comment by erf** [comment]
> Haha, this would give a labyrinth feeling :)

But you would still be able to explore the dungeon using `X`, as not to get too lost :)

**Comment by anaseto** [comment]
So I added a `-c` option to have a centered camera, with marked walls around borders. I still prefer static maps, I think, but it's good to have :)

**Comment by erf** [comment]
Thats really cool - but i also think i like the static map.
