### ISSUE TITLE
Incorrect version info on postmortem screen and in character dump file

### ISSUE THREAD

**Issue by VedVid** [anaseto/boohu#11]
It's still 0.4
![boohu](https://user-images.githubusercontent.com/16949680/39119462-342280a2-46ec-11e8-91b4-07c7a4cc727a.png)

**Comment by anaseto** [comment]
Yeah, I screwed this up :) Already bumped the version number in order not to forget next release in [this commit](https://github.com/anaseto/boohu/commit/da7fd2c3ce262539ceda7c6e26bff089766b31ae). This happened in part because I didn't follow well my own advice in #3,  because I created the binaries before creating the tag via github's release ui.
