### ISSUE TITLE
Action menu missing from the help menu

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#15]
The Action menu `M` keyboard shortcut is missing from the help menu `?`. I'm also thinking that the two menus, as of now at least, seem to have overlapping functionality as they are both showing a list of actions with key bindings. Perhaps they could be combined into one menu?

**Comment by anaseto** [comment]
Yes, this is a work in progress. Actually, the new menu was thought essentially so that the game is fully playable with the mouse, so I forgot about mentioning M :) And yes, most things can be combined, but for technical reasons some of them could not (yet). And description and exclusion only make sense in targeting mode, so I'm not sure what to do about them, but they'll probably require specific treatment.

We can keep this issue open until all the menu stuff is polished. Thanks for testing!

**Comment by anaseto** [comment]
So, I reworked menu stuff so that it is more useful for mouse users, adding several buttons that work in both targeting and normal mode, and the old menu is reduced and combined.  I have however eventually decided to remove the M keyboard shorcut, because this menu only really makes sense for mouse, as this functionality is already provided for keyboard uses by faster means, and I think it is better to shorten the help list.
